---
title: "Proposal"
---

## Class project proposal

Please prepare a 1-2 pp project proposal describing you you intend to fulfill this part of the course requirements. Your proposal should have the following components:

1. **Introduction**: Describe the question you will answer, the topic you will discuss, or the phenomenon you will demonstrate and why it is of interest to you and important to vision science.

2. **Methods**: Describe the components of your project, specifically whether you will be writing software, conducting an experiment, or reviewing the literature. All projects will have a written component (~8-12 pp write-up) and an in-class presentation component (20-30 min).

3. **Resources**: Cite the resources you have consulted in preparing your proposal. You may annotate the resources with brief comments if you wish.

## Submission details

Your proposal is due on Wednesday, February 28. 
You may submit electronically, via an emailed document or URL to a web site/page.

I am happy to consult with you about your proposal at any time.